server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/ibanking/tuition/auth/**
          filters:
            - AddRequestHeader=X-Gateway-Secret,my-super-secret

        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/ibanking/tuition/users/**
          filters:
            - AddRequestHeader=X-Gateway-Secret,my-super-secret

        - id: student-service
          uri: http://localhost:8084
          predicates:
            - Path=/ibanking/tuition/students/**
          filters:
            - AddRequestHeader=X-Gateway-Secret,my-super-secret

        - id: payment-service
          uri: http://localhost:8085
          predicates:
            - Path=/ibanking/tuition/payments/**
          filters:
            - AddRequestHeader=X-Gateway-Secret,my-super-secret

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:3001"
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
