server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8082
              predicates:
                - Path=/ibanking/tuition/auth/**
              filters:
                - AddRequestHeader=X-Gateway-Secret,my-super-secret


            - id: student-service
              uri: http://localhost:8084
              predicates:
                - Path=/ibanking/tuition/students/**
              filters:
                - AddRequestHeader=X-Gateway-Secret,my-super-secret
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
